server:
  port: 8000

spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
      routes:
        - id: authentication-api
          uri: ${AUTH_URI:http://localhost:8010}
          predicates:
            - Path=/auth/**
        - id: mail-api
          uri: ${MAIL_URI:http://localhost:8015}
          predicates:
            - Path=/mail/**
auth-control.autUrl: ${AUTH_CONTROL_URI:http://localhost:8010/auth/control-auth}



