apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gateway-public-ip
    kubernetes.io/ingress.allow-http: "false"
    netwroking.gke.io/managed-certificates: gateway-ssl
spec:
  backend:
    serviceName: gateway-service
    servicePort: 80